run_data_collection: True
create_dataset: True
create_s1_model: True

# Iterable Configs
detector_names: ['text_categorizer']
modeling_row_limits: [300, 1000]
  # quantizations: ['no_quantization', 'int8', 'int4']

# General Configs
application_name: sdk_automation
sub_application_name: patent_abstract_categorization
backend_config:
  backend_type: neuralsignal_v1
  mongo_url: mongodb://hp.lan:27017/
  mlflow_uri: "http://z600.lan:8000"
indirect_config:
  indirect_model: "google/flan-t5-large"
  zone_size: 1024
  indirect_batch_size: 100
  # no_quantization, int8 or int4
  quantization: "int8"
  device: "auto"

# Data collection
dataset: patent_abstract_categorization
max_new_tokens: 10
truncation_length: 2048
data_collection_row_limit: 1000
batch_size: 100

# Dataset builder
write_to_file: True
build_in_memory: False
file_out: patent_{detector}.csv
query:
zone_size: 1024
use_full_zone_names: False
dataset_row_limit: 100

# S1 Model Build
model_name: patent_abstract_categorization
description: patent_abstract_categorization
modeling_row_limit: 0
max_evals: 20
params:
  description: model_desc
tags:
  runner: dataset_automation
metadata:
  md: dataset_automation
