run_data_collection: True
create_dataset: True
create_s1_model: True

# Iterable Configs
detector_names: ['hallucination', 'hallucination2']
modeling_row_limits: [30, 40]
quantizations: ['no_quantization', 'int8', 'int4']

# General Configs
application_name: sdk_automation
sub_application_name: testing
backend_config:
  backend_type: neuralsignal_v1
  mongo_url: mongodb://hp.lan:27017/
  db: sdk_testing
  col: col
  mlflow_uri: "http://z600.lan:8000"
indirect_config:
  indirect_model: "t5-small"
  zone_size: 1024
  indirect_batch_size: 100
  # no_quantization, int8 or int4
  quantization: "no_quantization"
  device: "cpu"

# Data collection
dataset: halu_qa
max_new_tokens: 128
truncation_length: 2048
data_collection_row_limit: 20
batch_size: 10
use_full_zone_names: False

# Dataset builder
write_to_file: True
build_in_memory: True
file_out: default_{detector}.csv
query:
zone_size: 1024
use_full_zone_names: False
dataset_row_limit: 100

# S1 Model Build
model_name: default_model
description: model_desc
modeling_row_limit: 10
max_evals: 1
params:
  description: model_desc
tags:
  runner: dataset_automation
metadata:
  md: dataset_automation