run_data_collection: False
create_dataset: True
create_s1_model: True

# Iterable Configs
detector_names: ['hallucination']
modeling_row_limits: [10000]
  # quantizations: ['no_quantization', 'int8', 'int4']

# General Configs
application_name: sdk_automation_test
sub_application_name: hb
backend_config:
  backend_type: neuralsignal_v1
  mongo_url: mongodb://hp.lan:27017/
  mlflow_uri: "http://z600.lan:8000"
indirect_config:
  # indirect_model: "microsoft/Phi-3-mini-128k-instruct"
  # indirect_model: "google/flan-t5-xl"
  # indirect_model: "google-bert/bert-base-uncased"
  # indirect_model: "PatronusAI/Llama-3-Patronus-Lynx-8B-Instruct"
  indirect_model: "t5-small"
  indirect_batch_size: 1
  # no_quantization, int8 or int4
  quantization: "no_quantization"
  device: "cpu"

# Data collection
dataset: HaluBench
max_new_tokens: 1
truncation_length: 3000
data_collection_row_limit: 1000
batch_size: 1
preprocess_dataset: True
preprocess_params: {"source_ds": "DROP", "rows": 1000}

# indirect instrumentation config
indirect_instrumentation_config:
  instrument_encoder: True
  instrument_decoder: True
  instrument_attention: True
  instrument_FF: True
  instrument_embedding: True
  collector_config:
    mode: additive
    data_to_save: ["inputs", "outputs", "layer_info", "topology"]
    zone_size: 256
    zone_size_by_layer: {
      SelfAttention.o: 128,
      SelfAttention.v: 128,
    }
    layer_names_to_include: ['all'] # "all" to include all
    layer_indexes_to_include: []

# Dataset builder
write_to_file: True
build_in_memory: False
file_out: "{dataset}_{model}_{detector}.csv"
query: {}
zone_size: 1024
use_full_zone_names: True
dataset_row_limit: 20000
passthrough_fields: []
feature_set_configs: [
  {
    name: "zones",
    target_zone_size: {"default": 1024, "SelfAttention.o": 128, "SelfAttention.v": 128},
    field_to_process: "outputs",
    layer_names_to_include: ["SelfAttention.o", "SelfAttention.v", "act"],
    layer_indexes_to_include: [],
  }
]

# S1 Model Build
model_name: HaluBench
description: Zones only
modeling_row_limit: 0
max_evals: 5
seed: 43
params:
  description: model_desc
tags:
  runner: dataset_automation
metadata:
  md: dataset_automation
