run_data_collection: True
create_dataset: False
create_s1_model: False

# Iterable Configs
detector_names: ['llm-aggrefact']
modeling_row_limits: [1000]
  # quantizations: ['no_quantization', 'int8', 'int4']

# General Configs
application_name: llm-aggrefact
sub_application_name: llm-aggrefact_t5_xl
backend_config:
  backend_type: neuralsignal_v1
  mongo_url: mongodb://localhost:27017/
  mlflow_uri: "databricks"
  mlflow_experiment_path: "/Users/pablo@neuralsignal.ai/ns_mlflow"
  mlflow_register_model: False
  DATABRICKS_HOST: "https://adb-3426620886840199.19.azuredatabricks.net/"
  DATABRICKS_TOKEN: "dapi614c7116b0f6480963e9858ee06907c6-3"

indirect_config:
  # indirect_model: "microsoft/Phi-3-mini-128k-instruct"
  indirect_model: "google/flan-t5-xl"
  # indirect_model: "google-bert/bert-base-uncased"
  indirect_batch_size: 1
  # no_quantization, int8 or int4
  quantization: "int8"
  device: "auto"

# indirect instrumentation config
indirect_instrumentation_config:
  instrument_encoder: True
  instrument_decoder: True
  instrument_attention: True
  instrument_FF: True
  instrument_embedding: True
  collector_config:
    mode: additive
    data_to_save: ["inputs", "outputs", "layer_info", "topology"]
    zone_size: 512
    zone_size_by_layer: {
      default: 512,
    }
    layer_names_to_include: ['all'] # "all" to include all
    layer_indexes_to_include: []

# Data collection
dataset: llm-aggrefact
max_new_tokens: 1
truncation_length: 3000
data_collection_row_limit: 1000
batch_size: 1
preprocess_dataset: False
preprocess_params: {"source_ds": "DROP", "rows": 1000}

# Dataset builder
write_to_file: True
build_in_memory: False
file_out: "{dataset}_{model}_{detector}.csv"
query: {}
zone_size: 1024
use_full_zone_names: True
dataset_row_limit: 1000
passthrough_fields: []
feature_set_configs: [
  {
    name: "zones",
    target_zone_size: {"default": 1024},
    field_to_process: "outputs",
    layer_names_to_include: ["all"],
    layer_indexes_to_include: [],
  }
]


# S1 Model Build
model_name: llm-aggrefact
description: Zones only
create_reduced_feature_model: False
modeling_row_limit: 0
max_evals: 50
seed: 43
params:
  description: model_desc
tags:
  runner: dataset_automation
metadata:
  md: dataset_automation

